#!/usr/bin/env python3
"""Run more agents, and the fleet view, on the VPS stack (docs/vps.md, "More agents").

    python3 agentctl.py add legal /opt/agents/legal     # an agent at its own host name (legal.<your domain>)
    python3 agentctl.py add hr /opt/agents/hr --internal  # an agent under the sample's host (<host>/agents/hr)
    python3 agentctl.py fleet [--internal]              # the fleet view across all of them
    python3 agentctl.py platform --admins you@contoso.com  # Create agent in the console builds and starts agents
    python3 agentctl.py connect legal github,linear     # connectors (added in the console) this agent may use
    python3 agentctl.py templates add <name> <git-url>  # a template library for Create agent (agent-templates/)
    python3 agentctl.py list | remove legal | render
    docker compose up -d --build

The list lives in agents.yaml. From it this writes docker-compose.agents.yml (each agent with its own
sign-in proxy, built by the same Dockerfile as the sample), nginx/agentkit-<name>.conf (a starting nginx
site per host name), and COMPOSE_FILE in .env so ``docker compose`` picks both files up. It prints what's
left to do by hand: copying the nginx site into /etc/nginx (certbot then edits that copy, which this script
never touches again), certbot, and the Entra redirect URIs. Nothing outside this folder is changed.

Each agent gets its own host name (``<name>.<your domain>``), its own sign-in cookie, and its own Redis
database. They share the model settings in .env unless the agent's entry overrides them (``env:``).
"""

from __future__ import annotations

import argparse
import copy
import re
import sys
import time
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
REGISTRY = HERE / "agents.yaml"
CONNECTORS = HERE / "connectors.json"  # written by the platform service (the console's Connectors page)
GATEWAY = "http://platform:8001/mcp/{name}"
_CONNECTOR = re.compile(r"[a-z][a-z0-9_]{1,30}")
_TOKEN = re.compile(r"[A-Za-z0-9_-]{32,128}")
BASE = HERE / "docker-compose.yml"
OUT = HERE / "docker-compose.agents.yml"
NGINX = HERE / "nginx"
ENV = HERE / ".env"
COMPOSE_FILES = "docker-compose.yml:docker-compose.agents.yml"
FIRST_PORT = 4181
RESERVED = {"agent", "auth", "redis", "fleet", "www", "api", "sample", "platform"}
_NAME = re.compile(r"^[a-z][a-z0-9-]{0,30}[a-z0-9]$")
_HOST = re.compile(r"^(?=.{1,253}$)([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9-]{2,63}$")
_ENV_KEY = re.compile(r"^[A-Z][A-Z0-9_]*$")
# role checks need signed role claims (Easy Auth); without them a role setting would trust a plain header
_REFUSED_ENV = re.compile(r"(_ROLE|_ROLES)$|^AGENTKIT_(USER|USER_FALLBACK|PRINCIPAL_CLAIMS|USER_TOKEN)_HEADER$|^AGENTKIT_REQUIRE_USER$")
FLEET_CALLER = "x-forwarded-email: fleet@agentkit.local"
PREFIX_HEADER = "x-agentkit-prefix"  # set by the platform router; agents render their links under it
_EMAIL = re.compile(r"^[A-Za-z0-9._%+-]{1,64}@[A-Za-z0-9.-]{1,190}\.[A-Za-z]{2,24}$")
GENERATED = "# Generated by agentctl.py from agents.yaml. Edit agents.yaml and run `python3 agentctl.py render`.\n"


class Problem(SystemExit):
    def __init__(self, message: str):
        super().__init__(f"agentctl: {message}")


# ------------------------------------------------------------------------------------------ state
def read_env(path: Path = ENV) -> dict[str, str]:
    values: dict[str, str] = {}
    if path.is_file():
        for line in path.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                key, _, value = line.partition("=")
                values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def load(path: Path = REGISTRY) -> dict:
    data = yaml.safe_load(path.read_text(encoding="utf-8")) if path.is_file() else None
    data = data or {}
    data.setdefault("agents", [])
    data.setdefault("fleet", None)
    data.setdefault("platform", None)
    data.setdefault("sample", None)
    return data


def connectors() -> dict[str, dict]:
    import json

    if not CONNECTORS.is_file():
        return {}
    return dict((json.loads(CONNECTORS.read_text(encoding="utf-8") or "{}")).get("connectors") or {})


def policy_of(connector: dict) -> str:
    """The fingerprint of a connector's tool rules (the same as platform/connectors.py computes): the agent
    sends it with every tools request, and the gateway refuses a stale one."""
    import hashlib
    import json

    rules = json.dumps({"allowed": sorted(connector.get("allowed") or []), "approval": sorted(connector.get("approval") or [])},
                       sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(rules.encode()).hexdigest()[:16]


def connector_env(entry: dict, known: dict[str, dict]) -> dict[str, str]:
    """AGENTKIT_CONNECTORS for an agent: gateway URLs and tool rules, never a vendor credential."""
    import json

    names = [c for c in entry.get("connectors") or [] if c in known]
    if not names:
        return {}
    spec = [{"name": n, "title": known[n].get("title") or n, "url": GATEWAY.format(name=n),
             "allowed_tools": known[n].get("allowed") or [], "approval": known[n].get("approval") or [],
             "policy": policy_of(known[n])} for n in names]
    return {"AGENTKIT_CONNECTORS": json.dumps(spec, separators=(",", ":")).replace("$", "$$"),
            "AGENTKIT_CONNECTOR_TOKEN": entry["connector_token"]}


def save(data: dict, path: Path = REGISTRY) -> None:
    _private_write(path, "# The agents this stack runs besides the sample (agentctl.py manages it).\n"
                   + yaml.safe_dump(data, sort_keys=False))


def domain(env: dict[str, str]) -> str:
    host = env.get("AGENT_HOST", "")
    if "." not in host:
        raise Problem("set AGENT_HOST in .env first (the sample's host name, e.g. agent.203-0-113-7.sslip.io)")
    return host.split(".", 1)[1]


def used_ports(data: dict, base_port: int) -> set[int]:
    ports = {base_port} | {a["port"] for a in data["agents"] if a.get("port")}
    if data.get("fleet") and data["fleet"].get("port"):
        ports.add(data["fleet"]["port"])
    return ports


def _port_busy(port: int) -> bool:
    """Something on this host already listens there, or an nginx site forwards to it (a service that's
    down right now still owns its port)."""
    import socket

    with socket.socket() as probe:
        try:
            probe.bind(("127.0.0.1", port))
        except OSError:
            return True
    for site in Path("/etc/nginx/sites-enabled").glob("*") if Path("/etc/nginx/sites-enabled").is_dir() else []:
        if site.name.startswith("agentkit-"):
            continue
        try:
            text = site.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if re.search(rf"(127\.0\.0\.1|localhost):{port}\b", text):
            return True
    return False


def next_port(data: dict, base_port: int) -> int:
    port, used = FIRST_PORT, used_ports(data, base_port)
    while port in used or _port_busy(port):
        port += 1
    return port


def project_info(path: Path) -> dict[str, str]:
    """The agent's own service name (its project name) and team (from the template's answers file)."""
    import tomllib

    project = tomllib.loads((path / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    info = {"service": str(project["name"]), "version": str(project.get("version") or "0.0.0")}
    answers = path / ".copier-answers.yml"
    if answers.is_file():
        values = yaml.safe_load(answers.read_text(encoding="utf-8")) or {}
        if values.get("team"):
            info["team"] = str(values["team"])
        title = str(values.get("project_name") or "")
        if re.fullmatch(r"[A-Za-z0-9 .,()&+-]{1,60}", title):
            info["title"] = title  # shown in the console's list of agents
    return info


def check_agent_folder(path: Path) -> str:
    if not path.is_dir():
        raise Problem(f"{path} isn't a folder")
    if not (path / "pyproject.toml").is_file():
        raise Problem(f"{path} has no pyproject.toml: generate the agent first (console → Create agent)")
    apps = [p for p in (path / "src").glob("*/app.py") if p.parent.name.isidentifier()]
    if len(apps) != 1:
        raise Problem(f"{path} needs exactly one src/<package>/app.py (found {len(apps)})")
    if not (path / "tests" / "test_evals.py").is_file():
        raise Problem(f"{path} has no tests/test_evals.py: the build runs it as the quality gate")
    return apps[0].parent.name


def validate(data: dict) -> None:
    """Everything render() copies into compose, nginx and printed commands (agents.yaml may be hand-edited)."""
    seen_names, seen_hosts, seen_ports, seen_dbs = set(), set(), set(), set()
    entries = [("agent", a) for a in data["agents"]] + ([("fleet", data["fleet"])] if data.get("fleet") else [])
    for kind, e in entries:
        if not isinstance(e, dict):
            raise Problem(f"agents.yaml: every {kind} entry must be a mapping")
        internal = e.get("internal") is True
        if not internal:
            host, port = str(e.get("host", "")), e.get("port")
            if not _HOST.fullmatch(host) or host in seen_hosts:
                raise Problem(f"agents.yaml: bad or repeated host {host!r}")
            if not isinstance(port, int) or not 1024 < port < 65536 or port in seen_ports:
                raise Problem(f"agents.yaml: bad or repeated port {port!r} for {host}")
            seen_hosts.add(host)
            seen_ports.add(port)
        elif "host" in e or "port" in e:
            raise Problem(f"agents.yaml: an internal {kind} has no host or port")
        if kind == "fleet":
            continue
        name, db, path = str(e.get("name", "")), e.get("redis_db"), str(e.get("path", ""))
        if not _NAME.fullmatch(name) or name in RESERVED or name in seen_names:
            raise Problem(f"agents.yaml: bad or repeated name {name!r}")
        if not isinstance(db, int) or not 1 <= db <= 15 or db in seen_dbs:
            raise Problem(f"agents.yaml: bad or repeated redis_db {db!r} for {name}")
        if not Path(path).is_absolute() or any(c in path for c in "\n\r\"'$`;&|<>"):
            raise Problem(f"agents.yaml: path for {name} must be an absolute path without shell characters")
        for key in e.get("env") or {}:
            if not _ENV_KEY.fullmatch(str(key)) or _REFUSED_ENV.search(str(key)):
                raise Problem(f"agents.yaml: env {key!r} for {name} isn't allowed here")
        _check_connectors(name, e)
        for key in ("created_by", "created_at"):
            if key in e and not re.fullmatch(r"[A-Za-z0-9@._:+-]{1,120}", str(e[key])):
                raise Problem(f"agents.yaml: {key} for {name} has unexpected characters")
        seen_names.add(name)
        seen_dbs.add(db)
    if data.get("sample") is not None:
        if not isinstance(data["sample"], dict):
            raise Problem("agents.yaml: sample must be a mapping")
        _check_connectors("sample", data["sample"])
    tokens = [str(e.get("connector_token")) for e in [*data["agents"], data.get("sample") or {}]
              if isinstance(e, dict) and e.get("connector_token")]
    if len(tokens) != len(set(tokens)):
        raise Problem("agents.yaml: two agents share a connector_token; remove one and run connect again")
    platform = data.get("platform")
    if platform:
        admins = platform.get("admins") if isinstance(platform, dict) else None
        if not isinstance(admins, list) or not all(isinstance(a, str) and _EMAIL.fullmatch(a) for a in admins):
            raise Problem("agents.yaml: platform.admins must be a list of email addresses")
        folder = str(platform.get("agents_dir", ""))
        if not Path(folder).is_absolute() or any(c in folder for c in "\n\r\"'$`;&|<>:"):
            raise Problem("agents.yaml: platform.agents_dir must be an absolute path")


def _atomic_write(path: Path, text: str, mode: int | None = None) -> None:
    """Write beside the file and rename: readers (the platform router, docker compose) never see half a file,
    and a crash never loses the old one."""
    tmp = path.with_name(f".{path.name}.tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.chmod(mode if mode is not None else (path.stat().st_mode & 0o777 if path.exists() else 0o644))
    tmp.replace(path)


def _check_connectors(name: str, e: dict) -> None:
    listed = e.get("connectors") or []
    if not isinstance(listed, list) or not all(isinstance(c, str) and _CONNECTOR.fullmatch(c) for c in listed):
        raise Problem(f"agents.yaml: connectors for {name} must be connector names")
    if listed and not _TOKEN.fullmatch(str(e.get("connector_token") or "")):
        raise Problem(f"agents.yaml: {name} has connectors but no valid connector_token")


def _private_write(path: Path, text: str) -> None:
    """agents.yaml and the generated compose file can hold per-agent settings: owner-only, like .env."""
    _atomic_write(path, text, 0o600)


# ------------------------------------------------------------------------------------------ render
def _services(base: dict) -> tuple[dict, dict]:
    services = base.get("services") or {}
    if "agent" not in services or "auth" not in services:
        raise Problem("docker-compose.yml must define the 'agent' and 'auth' services")
    return services["agent"], services["auth"]


def agent_service(template: dict, agent: dict, known: dict[str, dict] | None = None) -> dict:
    service = copy.deepcopy(template)
    # the agent's folder is the build context (filtered by Dockerfile.dockerignore); the kit is this checkout
    service["build"] = {"context": agent["path"], "dockerfile": str(HERE / "Dockerfile"),
                        "additional_contexts": {"kit": str(HERE.parent.parent)}}
    env = service["environment"]
    env["AGENTKIT_SERVICE_NAME"] = agent.get("service") or agent["name"]
    env["AGENTKIT_SERVICE_VERSION"] = agent.get("version") or "0.0.0"
    env["AGENTKIT_TEAM"] = agent.get("team") or agent["name"]
    env["AGENTKIT_REDIS_URL"] = f"redis://redis:6379/{agent['redis_db']}"
    for key, value in (agent.get("env") or {}).items():
        env[key] = str(value).replace("$", "$$")  # literal: Compose would otherwise interpolate it
    env.update(connector_env(agent, known or {}))
    return service


def auth_service(template: dict, name: str, host: str, port: int, upstream: str) -> dict:
    service = copy.deepcopy(template)
    service["depends_on"] = [upstream]
    service["ports"] = [f"127.0.0.1:{port}:4180"]
    env = service["environment"]
    env["OAUTH2_PROXY_REDIRECT_URL"] = f"https://{host}/oauth2/callback"
    env["OAUTH2_PROXY_UPSTREAMS"] = f"http://{upstream}:8000"
    env["OAUTH2_PROXY_COOKIE_NAME"] = f"_agentkit_{name.replace('-', '_')}"
    return service


def fleet_service(data: dict, env: dict[str, str], version: str) -> dict:
    entries = [f"http://agent:8000||{env.get('SAMPLE_NAME', 'Order Status Agent')}|https://${{AGENT_HOST}}"]
    entries += [f"http://agent-{a['name']}:8000||{a['name']}|" + (f"https://${{AGENT_HOST}}/agents/{a['name']}" if a.get("internal")
                                                                   else f"https://{a['host']}") for a in data["agents"]]
    return {
        "build": {"context": "../..", "dockerfile": "fleet/Dockerfile"},
        "restart": "unless-stopped",
        "environment": {
            "AGENTKIT_ENVIRONMENT": "dev",
            "AGENTKIT_SERVICE_VERSION": version,
            "AGENTKIT_AUTH_MODE": "api_key",  # no Azure identity here: nothing to mint tokens with
            "AGENTKIT_REQUIRE_USER": "true",
            "AGENTKIT_USER_HEADER": "x-forwarded-email",
            "AGENTKIT_USER_FALLBACK_HEADER": "",
            "AGENTKIT_PRINCIPAL_CLAIMS_HEADER": "",  # no signed role claims here: role checks fail closed
            # how the fleet identifies itself to agents on this private network (they trust X-Forwarded-Email)
            "AGENTKIT_FLEET_CALLER_HEADER": FLEET_CALLER,
            "AGENTKIT_FLEET_AGENTS": ";".join(entries),
            "AGENTKIT_FORWARDED_PREFIX_HEADER": PREFIX_HEADER,  # served at <host>/fleet by the platform router
        },
        "expose": ["8000"],
    }


def platform_service(platform: dict) -> dict:
    """Builds and starts agents from the console (Create agent), and routes <host>/agents/<name> and
    <host>/fleet. It drives Docker on this host, so only the listed admins may create or remove agents,
    and it only answers requests that come through the sign-in proxy."""
    repo, agents_dir = str(HERE.parent.parent), platform["agents_dir"]
    return {
        "build": {"context": str(HERE / "platform"), "dockerfile": "Dockerfile"},
        "restart": "unless-stopped",
        "environment": {
            "PLATFORM_ADMINS": ",".join(platform["admins"]),
            "PLATFORM_HOME": repo,
            "PLATFORM_AGENTS_DIR": agents_dir,
            "PLATFORM_PUBLIC_HOST": "${AGENT_HOST}",
            "PLATFORM_TRUSTED_PEER": "auth",  # the sign-in proxy: the only caller it serves
            # encrypts connector credentials at rest (generated into .env by `agentctl.py platform`)
            "PLATFORM_SECRET_KEY": "${PLATFORM_SECRET_KEY:?run agentctl.py platform to create it}",
        },
        # the same paths as on the host: docker compose sends build contexts by path
        "volumes": ["/var/run/docker.sock:/var/run/docker.sock", f"{repo}:{repo}", f"{agents_dir}:{agents_dir}"],
        "expose": ["8000", "8001"],  # 8001: the connector gateway, for agents on this network only
        "depends_on": ["agent"],
    }


def nginx_site(host: str, port: int) -> str:
    return f"""# Generated by agentctl.py: a starting point. Copy it into /etc/nginx/sites-available (don't link it):
# certbot --nginx -d {host} --redirect then adds HTTPS to that copy, and agentctl.py never touches it.
server {{
    listen 80;
    server_name {host};
    location / {{
        proxy_pass http://127.0.0.1:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffer_size 16k;      # Entra sign-in cookies are large
        proxy_buffers 8 16k;
        proxy_buffering off;        # chat replies stream
        proxy_read_timeout 300s;
    }}
}}
"""


def render(data: dict, env: dict[str, str], *, base_path: Path = BASE, out: Path = OUT, nginx_dir: Path = NGINX) -> dict:
    validate(data)
    base = yaml.safe_load(base_path.read_text(encoding="utf-8"))
    agent_t, auth_t = _services(base)
    version = str(agent_t["environment"].get("AGENTKIT_SERVICE_VERSION", "0.0.0"))
    services: dict = {}
    sites: dict[str, str] = {}
    known = connectors()
    for a in data["agents"]:
        services[f"agent-{a['name']}"] = agent_service(agent_t, a, known)
        if not a.get("internal"):
            services[f"auth-{a['name']}"] = auth_service(auth_t, a["name"], a["host"], a["port"], f"agent-{a['name']}")
            sites[f"agentkit-{a['name']}.conf"] = nginx_site(a["host"], a["port"])
    if data.get("fleet"):
        f = data["fleet"]
        services["fleet"] = fleet_service(data, env, version.split(":-")[-1].rstrip("}"))
        if not f.get("internal"):
            services["auth-fleet"] = auth_service(auth_t, "fleet", f["host"], f["port"], "fleet")
            sites["agentkit-fleet.conf"] = nginx_site(f["host"], f["port"])
    if data.get("sample") and connector_env(data["sample"], known):
        services["agent"] = {"environment": connector_env(data["sample"], known)}  # merged into the sample's settings
    if data.get("platform"):
        services["platform"] = platform_service(data["platform"])
        # the sample's sign-in proxy now forwards to the platform router, which serves the sample at "/"
        services["auth"] = {"environment": {"OAUTH2_PROXY_UPSTREAMS": "http://platform:8000"}, "depends_on": ["platform"]}
    compose = {"services": services} if services else {"services": {}}
    _private_write(out, GENERATED + yaml.safe_dump(compose, sort_keys=False, width=200))
    nginx_dir.mkdir(exist_ok=True)
    for old in nginx_dir.glob("agentkit-*.conf"):
        if old.name not in sites:
            old.unlink()
    for name, text in sites.items():
        (nginx_dir / name).write_text(text, encoding="utf-8")
    return compose


def ensure_compose_file(path: Path = ENV) -> None:
    """docker compose reads COMPOSE_FILE from .env, so plain `docker compose ...` includes the agents.
    Files already listed there are kept."""
    text = path.read_text(encoding="utf-8") if path.is_file() else ""
    files: list[str] = []
    lines = []
    for line in text.splitlines():
        bare = line.strip().removeprefix("export ").strip()
        if bare.startswith("COMPOSE_FILE="):
            files += [f for f in bare.split("=", 1)[1].strip().strip('"').strip("'").split(":") if f]
        else:
            lines.append(line)
    for f in COMPOSE_FILES.split(":"):
        if f not in files:
            files.append(f)
    lines.append(f"COMPOSE_FILE={':'.join(files)}")
    _atomic_write(path, "\n".join(lines) + "\n")  # keeps .env's permissions


def hosts(data: dict, env: dict[str, str]) -> list[str]:
    names = [env["AGENT_HOST"]] if env.get("AGENT_HOST") else []
    names += [a["host"] for a in data["agents"] if a.get("host")]
    if data.get("fleet") and data["fleet"].get("host"):
        names.append(data["fleet"]["host"])
    return names


def next_steps(data: dict, env: dict[str, str], new_host: str | None = None, removed: str | None = None) -> str:
    client = env.get("ENTRA_CLIENT_ID") or "<ENTRA_CLIENT_ID>"
    uris = " ".join(f"https://{h}/oauth2/callback" for h in hosts(data, env))
    sign_in = (f"az ad app update --id {client} --web-redirect-uris {uris}\n"
               "              (this replaces the app's list: add any other redirect URIs it needs)")
    lines = ["", "Next:"]
    if new_host:
        site = next(p for p in NGINX.glob("agentkit-*.conf") if f"server_name {new_host};" in p.read_text())
        lines += [f"  1. nginx:   cp {site} /etc/nginx/sites-available/{site.name} && "
                  f"ln -sf /etc/nginx/sites-available/{site.name} /etc/nginx/sites-enabled/{site.name} && nginx -t && systemctl reload nginx",
                  f"  2. HTTPS:   certbot --nginx -d {new_host} --redirect",
                  f"  3. Sign-in: {sign_in}",
                  "  4. Start:   docker compose up -d --build",
                  f"  Then open https://{new_host}/console"]
    elif removed:
        lines += [f"  1. nginx:   rm -f /etc/nginx/sites-enabled/{removed} /etc/nginx/sites-available/{removed} && nginx -t && systemctl reload nginx",
                  "  2. Stop:    docker compose up -d --remove-orphans",
                  f"  3. Sign-in (optional, drops its redirect URI): {sign_in}"]
    else:
        lines += [f"  Sign-in redirect URIs: {sign_in}", "  docker compose up -d --build --remove-orphans"]
    return "\n".join(lines)


# ------------------------------------------------------------------------------------------ commands
def cmd_add(args, data, env) -> str:
    name = args.name.lower()
    if not _NAME.fullmatch(name) or name in RESERVED:
        raise Problem(f"name {name!r}: 2–32 lowercase letters, digits or dashes, not one of {sorted(RESERVED)}")
    if any(a["name"] == name for a in data["agents"]):
        raise Problem(f"{name} is already in agents.yaml (remove it first to change it)")
    path = Path(args.path).expanduser().resolve()
    check_agent_folder(path)
    dbs = {a["redis_db"] for a in data["agents"]}
    db = next((i for i in range(1, 16) if i not in dbs), None)
    if db is None:
        raise Problem("Redis has 16 databases: this stack is full (15 agents besides the sample)")
    if args.internal:
        entry: dict = {"name": name, "path": str(path), "internal": True, "redis_db": db, **project_info(path)}
        host = None
    else:
        host = (args.host or f"{name}.{domain(env)}").lower()
        if not _HOST.fullmatch(host) or host in hosts(data, env):
            raise Problem(f"host {host!r} is invalid or already used")
        entry = {"name": name, "path": str(path), "host": host,
                 "port": next_port(data, int(env.get("PROXY_PORT") or 4180)), "redis_db": db, **project_info(path)}
    if args.by:
        entry["created_by"] = args.by
        entry["created_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    for pair in args.env or []:
        key, sep, value = pair.partition("=")
        if not sep or not _ENV_KEY.fullmatch(key):
            raise Problem(f"--env {pair!r}: use KEY=value")
        if _REFUSED_ENV.search(key):
            raise Problem(f"--env {key}: sign-in and role settings can't be changed per agent here "
                          "(roles need signed claims, which only Easy Auth on Azure provides)")
        entry.setdefault("env", {})[key] = value
    data["agents"].append(entry)
    return host or ""


def cmd_fleet(args, data, env) -> str:
    if args.off:
        data["fleet"] = None
        return ""
    if args.internal:
        data["fleet"] = {"internal": True}
        return ""
    host = (args.host or f"fleet.{domain(env)}").lower()
    if not _HOST.fullmatch(host) or (host in hosts(data, env) and not (data.get("fleet") and data["fleet"]["host"] == host)):
        raise Problem(f"host {host!r} is invalid or already used")
    port = (data["fleet"]["port"] if data.get("fleet") and data["fleet"].get("port")
            else next_port(data, int(env.get("PROXY_PORT") or 4180)))
    data["fleet"] = {"host": host, "port": port}
    return host


def cmd_platform(args, data, env) -> None:
    if args.off:
        data["platform"] = None
        return
    admins = [a.strip().lower() for a in (args.admins or "").split(",") if a.strip()]
    if not admins:
        raise Problem("--admins: the email addresses allowed to create agents (comma-separated)")
    bad = [a for a in admins if not _EMAIL.fullmatch(a)]
    if bad:
        raise Problem(f"--admins: not email addresses: {bad}")
    folder = Path(args.agents_dir).expanduser().resolve()
    folder.mkdir(parents=True, exist_ok=True)
    data["platform"] = {"admins": admins, "agents_dir": str(folder)}
    ensure_secret_key()


def ensure_secret_key(path: Path = ENV) -> None:
    """The key the platform encrypts connector credentials with. Created once, kept in .env (owner-only)."""
    import base64
    import os

    if read_env(path).get("PLATFORM_SECRET_KEY"):
        return
    key = base64.urlsafe_b64encode(os.urandom(32)).decode()
    text = path.read_text(encoding="utf-8") if path.is_file() else ""
    _atomic_write(path, text.rstrip("\n") + ("\n" if text else "") +
                  "# encrypts connector credentials (agentctl.py platform); keep it with your backups of connectors.json\n"
                  f"PLATFORM_SECRET_KEY={key}\n", 0o600 if not path.exists() else None)


def cmd_connect(args, data, env) -> None:
    import secrets

    target = args.agent
    wanted = [] if args.connectors == "none" else [c.strip() for c in args.connectors.split(",") if c.strip()]
    known = connectors()
    bad = [c for c in wanted if not _CONNECTOR.fullmatch(c) or c not in known]
    if bad:
        raise Problem(f"not connectors on this server: {bad} (add them in the console first)")
    if target == "sample":
        entry = data.get("sample") or {}
        data["sample"] = entry
    else:
        entry = next((a for a in data["agents"] if a["name"] == target), None)
        if entry is None:
            raise Problem(f"no agent named {target}")
    entry["connectors"] = sorted(set(wanted))
    if wanted and not _TOKEN.fullmatch(str(entry.get("connector_token") or "")):
        entry["connector_token"] = secrets.token_urlsafe(32)  # identifies this agent to the connector gateway
    if not wanted:
        entry.pop("connector_token", None)


TEMPLATE_ROOT = HERE.parent.parent / "agent-templates"
_GIT_URL = re.compile(r"https://[A-Za-z0-9.-]+(?::[0-9]+)?/[A-Za-z0-9._~/-]+")
_GIT_REF = re.compile(r"[A-Za-z0-9._/-]{1,100}")


def _license_of(folder: Path) -> str:
    """A short name for the license file's first line, when it's a common one."""
    for name in ("LICENSE", "LICENSE.md", "LICENSE.txt", "COPYING"):
        path = folder / name
        if path.is_file() and not path.is_symlink():
            first = next((line.strip() for line in path.read_text(encoding="utf-8", errors="replace").splitlines()
                          if line.strip()), "")
            for pattern, short in (("MIT License", "MIT"), ("Apache License", "Apache-2.0"), ("BSD", "BSD"),
                                   ("Creative Commons", "Creative Commons"), ("GNU", "GPL family"), ("Mozilla", "MPL-2.0")):
                if pattern.lower() in first.lower():
                    return short
            return "see LICENSE"
    return ""


def cmd_templates(args) -> None:
    """Template libraries: agent personas that Create agent can start from (agent-templates/README.md)."""
    import shutil
    import subprocess
    sys.path.insert(0, str(HERE / "platform"))
    from templates import LIBRARY_NAME, load_catalog

    if args.action == "list":
        catalog = load_catalog(TEMPLATE_ROOT)
        if not catalog["libraries"]:
            print(f"no template libraries in {TEMPLATE_ROOT}")
        for lib in catalog["libraries"]:
            count = sum(len(g["templates"]) for g in lib["groups"])
            where = lib["source"] + (f" @ {lib['commit'][:7]}" if lib["commit"] else "")
            print(f"{lib['name']:<18}{count:>3} templates  {lib['title']}  {where}  {lib['license'] or 'no license given'}")
        return
    if not LIBRARY_NAME.fullmatch(args.name or ""):
        raise Problem("the library name: 2-41 lowercase letters, digits or dashes, starting with a letter")
    target = TEMPLATE_ROOT / args.name
    if args.action == "remove":
        if not target.is_dir():
            raise Problem(f"no template library named {args.name}")
        if not (target / ".git").is_dir():
            raise Problem(f"{args.name} ships with the kit; delete {target} by hand if you really want it gone")
        shutil.rmtree(target)
        print(f"removed {target}. Agents already made from it keep their instructions.")
        return
    if not args.url or not _GIT_URL.fullmatch(args.url):
        raise Problem("the git URL: https://host/owner/repo(.git)")
    if args.ref and (not _GIT_REF.fullmatch(args.ref) or args.ref.startswith("-")):
        raise Problem("--ref: a tag, branch or commit")
    if target.exists():
        raise Problem(f"{target} already exists (templates remove {args.name} first)")
    TEMPLATE_ROOT.mkdir(exist_ok=True)
    import os
    quiet = {**os.environ, "GIT_TERMINAL_PROMPT": "0"}  # a private or mistyped repo fails instead of asking for a password
    try:
        subprocess.run(["git", "clone", "--quiet", "--no-recurse-submodules", "--", args.url, str(target)], check=True, env=quiet)
        if args.ref:
            subprocess.run(["git", "-C", str(target), "checkout", "--quiet", args.ref], check=True)
        commit = subprocess.run(["git", "-C", str(target), "rev-parse", "HEAD"], check=True,
                                capture_output=True, text=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError) as exc:
        shutil.rmtree(target, ignore_errors=True)
        what = "is it public, and is the ref right?" if isinstance(exc, subprocess.CalledProcessError) else str(exc)
        raise Problem(f"couldn't clone {args.url} ({what})") from None
    if not (target / "library.yaml").exists():
        meta = {"title": args.name, "source": args.url, "commit": commit}
        license_name = _license_of(target)
        if license_name:
            meta["license"] = license_name
        (target / "library.yaml").write_text(yaml.safe_dump(meta, sort_keys=False), encoding="utf-8")
    catalog = load_catalog(TEMPLATE_ROOT)
    count = sum(1 for t in catalog["templates"].values() if t["library"] == args.name)
    if not count:
        shutil.rmtree(target, ignore_errors=True)
        raise Problem(f"{args.url} has no templates: markdown files with a `name:` in their front matter")
    print(f"added {args.name}: {count} templates from {args.url} at {commit[:12]}")
    print("Read them before anyone uses them: a template becomes an agent's instructions.")
    print("They're in the console now (Agents -> Create agent); no restart needed.")


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = parser.add_subparsers(dest="command", required=True)
    add = sub.add_parser("add", help="add an agent generated from the kit's template")
    add.add_argument("name")
    add.add_argument("path", help="the agent's folder (from copier copy / the console's Create agent)")
    add.add_argument("--host", help="default: <name>.<the domain of AGENT_HOST>")
    add.add_argument("--env", action="append", metavar="KEY=value", help="an extra setting for this agent (repeatable)")
    add.add_argument("--internal", action="store_true",
                     help="serve it under the sample's host (<host>/agents/<name>, needs `platform`) instead of its own")
    add.add_argument("--by", help=argparse.SUPPRESS)  # who asked (the platform service records it)
    fleet = sub.add_parser("fleet", help="turn the fleet view on (or --off)")
    fleet.add_argument("--host", help="default: fleet.<the domain of AGENT_HOST>")
    fleet.add_argument("--off", action="store_true")
    fleet.add_argument("--internal", action="store_true", help="only at <host>/fleet (needs `platform`)")
    plat = sub.add_parser("platform", help="let admins create and launch agents from the console (or --off)")
    plat.add_argument("--admins", help="comma-separated emails allowed to create and remove agents")
    plat.add_argument("--agents-dir", default="/opt/agents", help="where created agents are generated (default /opt/agents)")
    plat.add_argument("--off", action="store_true")
    rm = sub.add_parser("remove", help="remove an agent")
    rm.add_argument("name")
    con = sub.add_parser("connect", help="set the connectors an agent may use (names from the console, or none)")
    con.add_argument("agent", help="an agent's name, or sample")
    con.add_argument("connectors", help="comma-separated connector names, or none")
    sub.add_parser("list", help="show the agents")
    sub.add_parser("render", help="write the compose and nginx files again from agents.yaml")
    tpl = sub.add_parser("templates", help="template libraries for Create agent: list, add <name> <git-url>, remove <name>")
    tpl.add_argument("action", choices=["list", "add", "remove"])
    tpl.add_argument("name", nargs="?")
    tpl.add_argument("url", nargs="?")
    tpl.add_argument("--ref", help="a tag, branch or commit to check out (pin one for a reviewed version)")
    args = parser.parse_args(argv)
    if args.command == "templates":
        return cmd_templates(args)

    env, data = read_env(), load()
    new_host = removed = None
    if args.command == "list":
        print(f"sample  https://{env.get('AGENT_HOST', '?')}  (docker-compose.yml)")
        for a in data["agents"]:
            where = (f"https://{env.get('AGENT_HOST', '?')}/agents/{a['name']}" if a.get("internal")
                     else f"https://{a['host']}  port {a['port']}")
            extra = f"  connectors: {', '.join(a['connectors'])}" if a.get("connectors") else ""
            print(f"{a['name']:<8}{where}  {a['path']}  redis db {a['redis_db']}{extra}")
        if data.get("fleet"):
            f = data["fleet"]
            print("fleet   " + (f"https://{f['host']}  port {f['port']}" if f.get("host") else "")
                  + (f"  https://{env.get('AGENT_HOST', '?')}/fleet" if data.get("platform") else ""))
        if data.get("platform"):
            print(f"platform  admins: {', '.join(data['platform']['admins'])}  agents in {data['platform']['agents_dir']}")
        return
    if args.command == "add":
        new_host = cmd_add(args, data, env)
    elif args.command == "fleet":
        new_host = cmd_fleet(args, data, env) or None
        if args.off or args.internal:
            removed = "agentkit-fleet.conf"
    elif args.command == "platform":
        cmd_platform(args, data, env)
    elif args.command == "connect":
        cmd_connect(args, data, env)
    elif args.command == "remove":
        before = len(data["agents"])
        data["agents"] = [a for a in data["agents"] if a["name"] != args.name]
        if len(data["agents"]) == before:
            raise Problem(f"no agent named {args.name}")
        removed = f"agentkit-{args.name}.conf"
        gone = next(a for a in load()["agents"] if a["name"] == args.name)
        if gone.get("internal"):
            removed = None
    validate(data)  # before anything is written
    if data.get("platform"):
        ensure_secret_key()  # also for stacks set up before connectors existed
    save(data)
    render(data, env)
    ensure_compose_file()
    print(f"wrote agents.yaml, {OUT.name}, nginx/ and COMPOSE_FILE in .env")
    host = env.get("AGENT_HOST", "<AGENT_HOST>")
    if args.command == "add" and args.internal:
        note = "" if data.get("platform") else "\n  (turn the platform on first: python3 agentctl.py platform --admins you@example.com)"
        print(f"\nNext:\n  docker compose up -d --build\n  Then open https://{host}/agents/{args.name}/console{note}")
    elif args.command == "platform":
        print("\nNext:\n  docker compose up -d --build" + ("" if args.off else
              f"\n  Then open https://{host}/console/agents: admins can create and launch agents there"))
    elif args.command == "connect":
        svc = "agent" if args.agent == "sample" else f"agent-{args.agent}"
        print(f"\nNext:\n  docker compose up -d {svc}   (a restart with the new connectors; no rebuild)")
    elif args.command == "fleet" and args.internal:
        print(f"\nNext:\n  docker compose up -d --build --remove-orphans\n  Then open https://{host}/fleet"
              + ("" if data.get("platform") else "  (needs: python3 agentctl.py platform --admins ...)"))
    else:
        print(next_steps(data, env, new_host, removed))


if __name__ == "__main__":
    main(sys.argv[1:])
