#!/usr/bin/env python3
"""Run more agents, and the fleet view, on the VPS stack (docs/vps.md, "More agents").

    python3 agentctl.py add legal /opt/agents/legal     # an agent generated with the console's Create agent
    python3 agentctl.py fleet                           # the fleet view across all of them
    python3 agentctl.py list | remove legal | render
    docker compose up -d --build

The list lives in agents.yaml. From it this writes docker-compose.agents.yml (each agent with its own
sign-in proxy, built by the same Dockerfile as the sample), nginx/agentkit-<name>.conf (a starting nginx
site per host name), and COMPOSE_FILE in .env so ``docker compose`` picks both files up. It prints what's
left to do by hand: copying the nginx site into /etc/nginx (certbot then edits that copy, which this script
never touches again), certbot, and the Entra redirect URIs. Nothing outside this folder is changed.

Each agent gets its own host name (``<name>.<your domain>``), its own sign-in cookie, and its own Redis
database. They share the model settings in .env unless the agent's entry overrides them (``env:``).
"""

from __future__ import annotations

import argparse
import copy
import re
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
REGISTRY = HERE / "agents.yaml"
BASE = HERE / "docker-compose.yml"
OUT = HERE / "docker-compose.agents.yml"
NGINX = HERE / "nginx"
ENV = HERE / ".env"
COMPOSE_FILES = "docker-compose.yml:docker-compose.agents.yml"
FIRST_PORT = 4181
RESERVED = {"agent", "auth", "redis", "fleet", "www", "api"}
_NAME = re.compile(r"^[a-z][a-z0-9-]{0,30}[a-z0-9]$")
_HOST = re.compile(r"^(?=.{1,253}$)([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9-]{2,63}$")
_ENV_KEY = re.compile(r"^[A-Z][A-Z0-9_]*$")
# role checks need signed role claims (Easy Auth); without them a role setting would trust a plain header
_REFUSED_ENV = re.compile(r"(_ROLE|_ROLES)$|^AGENTKIT_(USER|USER_FALLBACK|PRINCIPAL_CLAIMS|USER_TOKEN)_HEADER$|^AGENTKIT_REQUIRE_USER$")
FLEET_CALLER = "x-forwarded-email: fleet@agentkit.local"
GENERATED = "# Generated by agentctl.py from agents.yaml. Edit agents.yaml and run `python3 agentctl.py render`.\n"


class Problem(SystemExit):
    def __init__(self, message: str):
        super().__init__(f"agentctl: {message}")


# ------------------------------------------------------------------------------------------ state
def read_env(path: Path = ENV) -> dict[str, str]:
    values: dict[str, str] = {}
    if path.is_file():
        for line in path.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                key, _, value = line.partition("=")
                values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def load(path: Path = REGISTRY) -> dict:
    data = yaml.safe_load(path.read_text(encoding="utf-8")) if path.is_file() else None
    data = data or {}
    data.setdefault("agents", [])
    data.setdefault("fleet", None)
    return data


def save(data: dict, path: Path = REGISTRY) -> None:
    _private_write(path, "# The agents this stack runs besides the sample (agentctl.py manages it).\n"
                   + yaml.safe_dump(data, sort_keys=False))


def domain(env: dict[str, str]) -> str:
    host = env.get("AGENT_HOST", "")
    if "." not in host:
        raise Problem("set AGENT_HOST in .env first (the sample's host name, e.g. agent.203-0-113-7.sslip.io)")
    return host.split(".", 1)[1]


def used_ports(data: dict, base_port: int) -> set[int]:
    ports = {base_port} | {a["port"] for a in data["agents"]}
    if data.get("fleet"):
        ports.add(data["fleet"]["port"])
    return ports


def next_port(data: dict, base_port: int) -> int:
    port, used = FIRST_PORT, used_ports(data, base_port)
    while port in used:
        port += 1
    return port


def project_info(path: Path) -> dict[str, str]:
    """The agent's own service name (its project name) and team (from the template's answers file)."""
    import tomllib

    project = tomllib.loads((path / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    info = {"service": str(project["name"]), "version": str(project.get("version") or "0.0.0")}
    answers = path / ".copier-answers.yml"
    if answers.is_file():
        team = (yaml.safe_load(answers.read_text(encoding="utf-8")) or {}).get("team")
        if team:
            info["team"] = str(team)
    return info


def check_agent_folder(path: Path) -> str:
    if not path.is_dir():
        raise Problem(f"{path} isn't a folder")
    if not (path / "pyproject.toml").is_file():
        raise Problem(f"{path} has no pyproject.toml: generate the agent first (console → Create agent)")
    apps = [p for p in (path / "src").glob("*/app.py") if p.parent.name.isidentifier()]
    if len(apps) != 1:
        raise Problem(f"{path} needs exactly one src/<package>/app.py (found {len(apps)})")
    if not (path / "tests" / "test_evals.py").is_file():
        raise Problem(f"{path} has no tests/test_evals.py: the build runs it as the quality gate")
    return apps[0].parent.name


def validate(data: dict) -> None:
    """Everything render() copies into compose, nginx and printed commands (agents.yaml may be hand-edited)."""
    seen_names, seen_hosts, seen_ports, seen_dbs = set(), set(), set(), set()
    entries = [("agent", a) for a in data["agents"]] + ([("fleet", data["fleet"])] if data.get("fleet") else [])
    for kind, e in entries:
        if not isinstance(e, dict):
            raise Problem(f"agents.yaml: every {kind} entry must be a mapping")
        host, port = str(e.get("host", "")), e.get("port")
        if not _HOST.match(host) or host in seen_hosts:
            raise Problem(f"agents.yaml: bad or repeated host {host!r}")
        if not isinstance(port, int) or not 1024 < port < 65536 or port in seen_ports:
            raise Problem(f"agents.yaml: bad or repeated port {port!r} for {host}")
        seen_hosts.add(host)
        seen_ports.add(port)
        if kind == "fleet":
            continue
        name, db, path = str(e.get("name", "")), e.get("redis_db"), str(e.get("path", ""))
        if not _NAME.match(name) or name in RESERVED or name in seen_names:
            raise Problem(f"agents.yaml: bad or repeated name {name!r}")
        if not isinstance(db, int) or not 1 <= db <= 15 or db in seen_dbs:
            raise Problem(f"agents.yaml: bad or repeated redis_db {db!r} for {name}")
        if not Path(path).is_absolute() or any(c in path for c in "\n\r\"'$`;&|<>"):
            raise Problem(f"agents.yaml: path for {name} must be an absolute path without shell characters")
        for key in e.get("env") or {}:
            if not _ENV_KEY.match(str(key)) or _REFUSED_ENV.search(str(key)):
                raise Problem(f"agents.yaml: env {key!r} for {name} isn't allowed here")
        seen_names.add(name)
        seen_dbs.add(db)


def _private_write(path: Path, text: str) -> None:
    """agents.yaml and the generated compose file can hold per-agent settings: owner-only, like .env."""
    path.touch(mode=0o600, exist_ok=True)
    path.chmod(0o600)
    path.write_text(text, encoding="utf-8")


# ------------------------------------------------------------------------------------------ render
def _services(base: dict) -> tuple[dict, dict]:
    services = base.get("services") or {}
    if "agent" not in services or "auth" not in services:
        raise Problem("docker-compose.yml must define the 'agent' and 'auth' services")
    return services["agent"], services["auth"]


def agent_service(template: dict, agent: dict) -> dict:
    service = copy.deepcopy(template)
    # the agent's folder is the build context (filtered by Dockerfile.dockerignore); the kit is this checkout
    service["build"] = {"context": agent["path"], "dockerfile": str(HERE / "Dockerfile"),
                        "additional_contexts": {"kit": str(HERE.parent.parent)}}
    env = service["environment"]
    env["AGENTKIT_SERVICE_NAME"] = agent.get("service") or agent["name"]
    env["AGENTKIT_SERVICE_VERSION"] = agent.get("version") or "0.0.0"
    env["AGENTKIT_TEAM"] = agent.get("team") or agent["name"]
    env["AGENTKIT_REDIS_URL"] = f"redis://redis:6379/{agent['redis_db']}"
    for key, value in (agent.get("env") or {}).items():
        env[key] = str(value).replace("$", "$$")  # literal: Compose would otherwise interpolate it
    return service


def auth_service(template: dict, name: str, host: str, port: int, upstream: str) -> dict:
    service = copy.deepcopy(template)
    service["depends_on"] = [upstream]
    service["ports"] = [f"127.0.0.1:{port}:4180"]
    env = service["environment"]
    env["OAUTH2_PROXY_REDIRECT_URL"] = f"https://{host}/oauth2/callback"
    env["OAUTH2_PROXY_UPSTREAMS"] = f"http://{upstream}:8000"
    env["OAUTH2_PROXY_COOKIE_NAME"] = f"_agentkit_{name.replace('-', '_')}"
    return service


def fleet_service(data: dict, env: dict[str, str], version: str) -> dict:
    entries = [f"http://agent:8000||{env.get('SAMPLE_NAME', 'Order Status Agent')}|https://${{AGENT_HOST}}"]
    entries += [f"http://agent-{a['name']}:8000||{a['name']}|https://{a['host']}" for a in data["agents"]]
    return {
        "build": {"context": "../..", "dockerfile": "fleet/Dockerfile"},
        "restart": "unless-stopped",
        "environment": {
            "AGENTKIT_ENVIRONMENT": "dev",
            "AGENTKIT_SERVICE_VERSION": version,
            "AGENTKIT_AUTH_MODE": "api_key",  # no Azure identity here: nothing to mint tokens with
            "AGENTKIT_REQUIRE_USER": "true",
            "AGENTKIT_USER_HEADER": "x-forwarded-email",
            "AGENTKIT_USER_FALLBACK_HEADER": "",
            "AGENTKIT_PRINCIPAL_CLAIMS_HEADER": "",  # no signed role claims here: role checks fail closed
            # how the fleet identifies itself to agents on this private network (they trust X-Forwarded-Email)
            "AGENTKIT_FLEET_CALLER_HEADER": FLEET_CALLER,
            "AGENTKIT_FLEET_AGENTS": ";".join(entries),
        },
        "expose": ["8000"],
    }


def nginx_site(host: str, port: int) -> str:
    return f"""# Generated by agentctl.py: a starting point. Copy it into /etc/nginx/sites-available (don't link it):
# certbot --nginx -d {host} --redirect then adds HTTPS to that copy, and agentctl.py never touches it.
server {{
    listen 80;
    server_name {host};
    location / {{
        proxy_pass http://127.0.0.1:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffer_size 16k;      # Entra sign-in cookies are large
        proxy_buffers 8 16k;
        proxy_buffering off;        # chat replies stream
        proxy_read_timeout 300s;
    }}
}}
"""


def render(data: dict, env: dict[str, str], *, base_path: Path = BASE, out: Path = OUT, nginx_dir: Path = NGINX) -> dict:
    validate(data)
    base = yaml.safe_load(base_path.read_text(encoding="utf-8"))
    agent_t, auth_t = _services(base)
    version = str(agent_t["environment"].get("AGENTKIT_SERVICE_VERSION", "0.0.0"))
    services: dict = {}
    sites: dict[str, str] = {}
    for a in data["agents"]:
        services[f"agent-{a['name']}"] = agent_service(agent_t, a)
        services[f"auth-{a['name']}"] = auth_service(auth_t, a["name"], a["host"], a["port"], f"agent-{a['name']}")
        sites[f"agentkit-{a['name']}.conf"] = nginx_site(a["host"], a["port"])
    if data.get("fleet"):
        f = data["fleet"]
        services["fleet"] = fleet_service(data, env, version.split(":-")[-1].rstrip("}"))
        services["auth-fleet"] = auth_service(auth_t, "fleet", f["host"], f["port"], "fleet")
        sites["agentkit-fleet.conf"] = nginx_site(f["host"], f["port"])
    compose = {"services": services} if services else {"services": {}}
    _private_write(out, GENERATED + yaml.safe_dump(compose, sort_keys=False, width=200))
    nginx_dir.mkdir(exist_ok=True)
    for old in nginx_dir.glob("agentkit-*.conf"):
        if old.name not in sites:
            old.unlink()
    for name, text in sites.items():
        (nginx_dir / name).write_text(text, encoding="utf-8")
    return compose


def ensure_compose_file(path: Path = ENV) -> None:
    """docker compose reads COMPOSE_FILE from .env, so plain `docker compose ...` includes the agents.
    Files already listed there are kept."""
    text = path.read_text(encoding="utf-8") if path.is_file() else ""
    files: list[str] = []
    lines = []
    for line in text.splitlines():
        bare = line.strip().removeprefix("export ").strip()
        if bare.startswith("COMPOSE_FILE="):
            files += [f for f in bare.split("=", 1)[1].strip().strip('"').strip("'").split(":") if f]
        else:
            lines.append(line)
    for f in COMPOSE_FILES.split(":"):
        if f not in files:
            files.append(f)
    lines.append(f"COMPOSE_FILE={':'.join(files)}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def hosts(data: dict, env: dict[str, str]) -> list[str]:
    names = [env["AGENT_HOST"]] if env.get("AGENT_HOST") else []
    names += [a["host"] for a in data["agents"]]
    if data.get("fleet"):
        names.append(data["fleet"]["host"])
    return names


def next_steps(data: dict, env: dict[str, str], new_host: str | None = None, removed: str | None = None) -> str:
    client = env.get("ENTRA_CLIENT_ID") or "<ENTRA_CLIENT_ID>"
    uris = " ".join(f"https://{h}/oauth2/callback" for h in hosts(data, env))
    sign_in = (f"az ad app update --id {client} --web-redirect-uris {uris}\n"
               "              (this replaces the app's list: add any other redirect URIs it needs)")
    lines = ["", "Next:"]
    if new_host:
        site = next(p for p in NGINX.glob("agentkit-*.conf") if f"server_name {new_host};" in p.read_text())
        lines += [f"  1. nginx:   cp {site} /etc/nginx/sites-available/{site.name} && "
                  f"ln -sf /etc/nginx/sites-available/{site.name} /etc/nginx/sites-enabled/{site.name} && nginx -t && systemctl reload nginx",
                  f"  2. HTTPS:   certbot --nginx -d {new_host} --redirect",
                  f"  3. Sign-in: {sign_in}",
                  "  4. Start:   docker compose up -d --build",
                  f"  Then open https://{new_host}/console"]
    elif removed:
        lines += [f"  1. nginx:   rm -f /etc/nginx/sites-enabled/{removed} /etc/nginx/sites-available/{removed} && nginx -t && systemctl reload nginx",
                  "  2. Stop:    docker compose up -d --remove-orphans",
                  f"  3. Sign-in (optional, drops its redirect URI): {sign_in}"]
    else:
        lines += [f"  Sign-in redirect URIs: {sign_in}", "  docker compose up -d --build --remove-orphans"]
    return "\n".join(lines)


# ------------------------------------------------------------------------------------------ commands
def cmd_add(args, data, env) -> str:
    name = args.name.lower()
    if not _NAME.match(name) or name in RESERVED:
        raise Problem(f"name {name!r}: 2–32 lowercase letters, digits or dashes, not one of {sorted(RESERVED)}")
    if any(a["name"] == name for a in data["agents"]):
        raise Problem(f"{name} is already in agents.yaml (remove it first to change it)")
    path = Path(args.path).expanduser().resolve()
    check_agent_folder(path)
    host = (args.host or f"{name}.{domain(env)}").lower()
    if not _HOST.match(host) or host in hosts(data, env):
        raise Problem(f"host {host!r} is invalid or already used")
    base_port = int(env.get("PROXY_PORT") or 4180)
    dbs = {a["redis_db"] for a in data["agents"]}
    db = next((i for i in range(1, 16) if i not in dbs), None)
    if db is None:
        raise Problem("Redis has 16 databases: this stack is full (15 agents besides the sample)")
    entry = {"name": name, "path": str(path), "host": host, "port": next_port(data, base_port), "redis_db": db,
             **project_info(path)}
    for pair in args.env or []:
        key, sep, value = pair.partition("=")
        if not sep or not _ENV_KEY.match(key):
            raise Problem(f"--env {pair!r}: use KEY=value")
        if _REFUSED_ENV.search(key):
            raise Problem(f"--env {key}: sign-in and role settings can't be changed per agent here "
                          "(roles need signed claims, which only Easy Auth on Azure provides)")
        entry.setdefault("env", {})[key] = value
    data["agents"].append(entry)
    return host


def cmd_fleet(args, data, env) -> str:
    if args.off:
        data["fleet"] = None
        return ""
    host = (args.host or f"fleet.{domain(env)}").lower()
    if not _HOST.match(host) or (host in hosts(data, env) and not (data.get("fleet") and data["fleet"]["host"] == host)):
        raise Problem(f"host {host!r} is invalid or already used")
    port = data["fleet"]["port"] if data.get("fleet") else next_port(data, int(env.get("PROXY_PORT") or 4180))
    data["fleet"] = {"host": host, "port": port}
    return host


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = parser.add_subparsers(dest="command", required=True)
    add = sub.add_parser("add", help="add an agent generated from the kit's template")
    add.add_argument("name")
    add.add_argument("path", help="the agent's folder (from copier copy / the console's Create agent)")
    add.add_argument("--host", help="default: <name>.<the domain of AGENT_HOST>")
    add.add_argument("--env", action="append", metavar="KEY=value", help="an extra setting for this agent (repeatable)")
    fleet = sub.add_parser("fleet", help="turn the fleet view on (or --off)")
    fleet.add_argument("--host", help="default: fleet.<the domain of AGENT_HOST>")
    fleet.add_argument("--off", action="store_true")
    rm = sub.add_parser("remove", help="remove an agent")
    rm.add_argument("name")
    sub.add_parser("list", help="show the agents")
    sub.add_parser("render", help="write the compose and nginx files again from agents.yaml")
    args = parser.parse_args(argv)

    env, data = read_env(), load()
    new_host = removed = None
    if args.command == "list":
        print(f"sample  https://{env.get('AGENT_HOST', '?')}  (docker-compose.yml)")
        for a in data["agents"]:
            print(f"{a['name']:<8}https://{a['host']}  {a['path']}  port {a['port']}  redis db {a['redis_db']}")
        if data.get("fleet"):
            print(f"fleet   https://{data['fleet']['host']}  port {data['fleet']['port']}")
        return
    if args.command == "add":
        new_host = cmd_add(args, data, env)
    elif args.command == "fleet":
        new_host = cmd_fleet(args, data, env) or None
        if args.off:
            removed = "agentkit-fleet.conf"
    elif args.command == "remove":
        before = len(data["agents"])
        data["agents"] = [a for a in data["agents"] if a["name"] != args.name]
        if len(data["agents"]) == before:
            raise Problem(f"no agent named {args.name}")
        removed = f"agentkit-{args.name}.conf"
    validate(data)  # before anything is written
    save(data)
    render(data, env)
    ensure_compose_file()
    print(f"wrote agents.yaml, {OUT.name}, nginx/ and COMPOSE_FILE in .env")
    print(next_steps(data, env, new_host, removed))


if __name__ == "__main__":
    main(sys.argv[1:])
